// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	auth2 "go-gin-api/api/auth"
	"go-gin-api/domain/auth"
	"go-gin-api/infrastructure"
)

// Injectors from injector.go:

func InitializedApp() *gin.Engine {
	db := infrastructure.ConnectToDatabase()
	userRepositoryImpl := auth.NewUserRepository(db)
	userServiceImpl := auth.NewAuthService(userRepositoryImpl)
	userHandlerImpl := auth2.NewHandlerAuth(userServiceImpl)
	engine := infrastructure.SetupRoutes(userHandlerImpl)
	return engine
}

// injector.go:

var userSet = wire.NewSet(auth.NewUserRepository, wire.Bind(new(auth.Repository), new(*auth.RepositoryImpl)), auth.NewAuthService, wire.Bind(new(auth.Service), new(*auth.ServiceImpl)), auth2.NewHandlerAuth, wire.Bind(new(auth2.Handler), new(*auth2.HandlerImpl)))
